### ISSUE TITLE
[K8s Contrib] Is there a way to parse a CRD into a K8sResource?

### ISSUE THREAD

**Issue by mruoss** [apple/pkl-pantry#18]
Hi

Pkl and its packages around Kubernetes (`pkl-k8s` and `k8s.contrib`) are impressive. I could not find a way to turn a CRD into a module extending `K8sResource` from `pkl-k8s`. Is there such functionality at the moment?

**Comment by stackoverflow** [comment]
Pr #17 may be what you are looking for. It's not merged yet, though.

**Comment by mruoss** [comment]
Oooh yes, that looks rad! Thanks for the heads up!

**Comment by Avarei** [comment]
I just saw that it is merged now fyi 😊

**Comment by mruoss** [comment]
Right thanks.
