### ISSUE TITLE
[OpenAPI v3] SchemaGenerator does not work with ModuleOutput

### ISSUE THREAD

**Issue by Avarei** [apple/pkl-pantry#26]
While trying to turn a Kubernetes CRD into a Pkl Module and then turning it back into a OpenAPIv3Spec I noticed that K8sObjects from pkl-k8s can not be converted.

Resulting in the following Error:
```
Unsure how to cast this type: new UnknownType {}
```

This seems to be due to the [ModuleOutput](https://pkl-lang.org/package-docs/pkl/current/base/ModuleOutput.html) present in [k8sObject](https://github.com/apple/pkl-k8s/blob/k8s%401.0.1/generated-package/K8sObject.pkl#L146).

I was able to Fix this by adding another filter for `prop.name != "output"` to:
https://github.com/apple/pkl-pantry/blob/8685ad681b4fa54bdb7355ef9b665f61bad84959/packages/org.openapis.v3/SchemaGenerator.pkl#L293-L295

As I am quite new to Pkl I am not sure if there is a better way to check if a property is a ModuleOutput.
I am also not sure if the output could be used with backticks as a regular property.

If you are interested I'm happy to create a PR.

**Comment by bioball** [comment]
Thanks for reporting! Fixed in #30
