### ISSUE TITLE
Error running the k8s converter on windows

### ISSUE THREAD

**Issue by luistrigueiros** [apple/pkl-pantry#6]
I have tried to run the k8s sample converter on a windows machine and got an error, but I has able to do the conversion on a Linux Alpine installation running in WSL

The failed windows run:
![screenshot 9](https://github.com/apple/pkl-pantry/assets/590567/61c84444-2a72-45ae-89f9-141c79350607)

The happy path by running on Linux:

![screenshot 8](https://github.com/apple/pkl-pantry/assets/590567/2955e74c-682e-432d-aa59-489800e1e235)

**Comment by bioball** [comment]
Thanks for the bug report. Pkl does not yet support Windows, you can track https://github.com/apple/pkl/issues/20 for when it will get supported.
